In [2]:
# eigenvalue computation for a set of matrices 
import numpy as np
from scipy.linalg import eig, eigh
from scipy.sparse.linalg import eigs, eigsh

In [9]:
# matrix names
names = ['covtype','census','optical']
prefix = "data/"

In [10]:
for n in names:
    # load matrix
    m =  np.loadtxt(prefix + n,delimiter=",")
    print("### Matrix:", n, "  shape: %dx%d" % m.shape )
    eival, eivec = eigsh(m.T@m, 1, which='LM')
    print(eivec[:5])
    print(" Largest eigenvalue:", eival)

Matrix: covtype   shape: 581012x54
[[-0.63668625]
 [-0.03281892]
 [-0.00285907]
 [-0.05895208]
 [-0.00967113]]
Largest eigenvalue: [1.17156973e+13]
Matrix: census   shape: 2458285x68
[[-0.00923417]
 [-0.02592876]
 [-0.01135386]
 [-0.00027961]
 [-0.00114585]]
Largest eigenvalue: [1.36554489e+10]
Matrix: optical   shape: 325834x174
[[2.41621151e-05]
 [3.87080061e-05]
 [2.46962275e-05]
 [2.97894409e-05]
 [2.32312765e-05]]
Largest eigenvalue: [1.07774949e+17]
