In [ ]:
## Sample operations of csv matrices, 

In [1]:
import numpy as np

In [2]:
# load matrix from csv file
a = np.loadtxt("data/covtype",delimiter=",")

In [3]:
a.shape, a.dtype

((581012, 54), dtype('float64'))

In [4]:
# create x vector containing 1's
x = np.array([1]*a.shape[1])

In [5]:
# elements are int (use [1.0]*54 to get floats)
x.shape, x.dtype

((54,), dtype('int64'))

In [6]:
# right multiplication 
y = a @ x

In [7]:
# entries are now float
y.shape, y.dtype

((581012,), dtype('float64'))

In [8]:
y[:20]

array([10300., 10077., 13195., 13219.,  9963.,  9709., 10409., 10298.,
       10456., 10378., 10629., 13361., 12989., 10640.,  9626.,  9513.,
       10310.,  9479.,  9475.,  9531.])

In [9]:
# left multiplication
z = y @ a

In [10]:
# orrible display format
z[:20]

array([1.45496438e+13, 7.57939057e+11, 6.56558008e+10, 1.37201964e+12,
       2.27139888e+11, 1.33325074e+13, 1.03260420e+12, 1.08996598e+12,
       6.97072521e+11, 1.10590335e+13, 2.52628526e+09, 2.25296661e+08,
       1.92493032e+09, 1.78077606e+08, 1.29924510e+07, 4.32262690e+07,
       2.48256980e+07, 7.88390860e+07, 7.00292900e+06, 3.38078450e+07])

In [11]:
# to get a better representation we need to change the print options
np.get_printoptions()

{'edgeitems': 3,
 'floatmode': 'maxprec',
 'formatter': None,
 'infstr': 'inf',
 'legacy': False,
 'linewidth': 75,
 'nanstr': 'nan',
 'precision': 8,
 'sign': '-',
 'suppress': False,
 'threshold': 1000}

In [12]:
# our entries are ints: no decimals and don't use scientific notation
float_formatter = "{:.0f}".format
np.set_printoptions(formatter={'float_kind':float_formatter})

In [13]:
# now we can see all the digits
# these are exactly the values in the readme file!
z[:20]

array([14549643830975, 757939056719, 65655800755, 1372019643035,
       227139887795, 13332507438427, 1032604199658, 1089965982517,
       697072520994, 11059033547178, 2526285260, 225296661, 1924930316,
       178077606, 12992451, 43226269, 24825698, 78839086, 7002929,
       33807845])